name: "HEROKU-DEPLOY-STATING"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: idoberko2/dokku-deploy-github-action@v1
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "react-sandbox-app"
          heroku_email: "ibeanuhillary@gmail.com"   
      - name: Run a one-line script
        run: echo successfully run
